application: tech-interview-master
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /img
  static_dir: images

- url: /css
  static_dir: stylesheets

- url: /js
  static_dir: javascript

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest