application: tech-interview-master
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: helloworld.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest